### ISSUE TITLE
Object parameter problems in julia 0.7

### ISSUE THREAD

**Issue by hhoeschle** [Spine-project/SpineOpt.jl#2]
Hi,

I use the Spine-Model in 0.7 (I know it is not supported yet).

I ran into problems calling object parameters:
```julia
some_t = Temporals()[1] # my ObjectClass is called Temporals
@show tx_year()[some_t] # WORKING
@show tx_year(Temporals = some_t) # NOT WORKING
```

the issue arises in the file `from_spine.jl` line 185. After a bit of testing the following solution fixes the problem:
```julia
...
elseif length(kwargs) == 1
    # key, value = kwargs[1] # OLD
    key = nothing
    value = nothing
    for (k,v) in kwargs
        key=k
        value =v
    end
    object_class_name = key  # NOTE: not in use at the moment
    object_name = value
...
```
It might not be the best solution, but I hope it helps transferring the module to julia  >= 0.7.

It works for me now :)

**Comment by manuelma** [comment]
Thanks @hhoeschle I'll look into it.

**Comment by mihlema** [comment]
We now support julia >=1.2, and the issue has been resolved. Closing this issue now.
