### ISSUE TITLE
Current implementation of representative days including seasonal storages and next steps

### ISSUE THREAD

**Issue by mihlema** [Spine-project/SpineOpt.jl#319]
This issue serves as a place to discuss the current implementation of rep. days with seasonal storages, and next steps and possible improvements.\
### The following elements are required database side:
- `model` object
    - parameter: `use_representative_days`:	`use_representative_days_w_seasonal_storage`
- `temporal_block` object
    - (at least) 1 `temporal_block` covering the non-representative period (e.g. `1year`)
        - parameter: `ordering_periods`: Map 
    e.g. `{"type": "map", "index_type": "date_time", "data": 
[["2017-01-01T00:00:00", {"type": "date_time", "data": "2017-01-02T00:00:00"}], 
["2017-01-01T01:00:00", {"type": "date_time", "data": "2017-01-02T01:00:00"}], 
...
["2017-12-31T23:00:00", {"type": "date_time", "data": "2017-02-26T23:00:00"}]]}`
        - the `ordering_periods` mapping parameter maps each timestep of the non-representative days to the corresponding timesteps of the representative days<sup>1</sup>
    - (at least) 1 `temporal_block` representing the representative period (e.g. `Rep-day1`)
        - Parameter: Ordering_periods
---
<sup>1</sup> I'm currently revising this to a mapping parameter, were only the start of a non-representative period (e.g. the start of each day) is required, mapping to a representative temporal_block.

### Code-side this translates to the following adjustments:
- `Variable_indices` functions:
    - indices function do now have a temporal_block keyword. The default for this temporal_block argument is `setdiff(temporal_block(), indices(ordering_periods))`, meaning that the default for the indices functions are the representative indices 
(Note: this doesn't have an impact for optimizations without representative days, as the `ordering_periods` parameter doesn't exist in this case, and the temporal_block will be equal to `anything`)
    - The only exceptions are variables, that we explicitly want to explicitly model over the whole timeframe, in particular the `node_state` variable. A node can be made a seasonal storage by connecting it to both, the rep.day temporal_blocks *and* the non-representative period (e.g. the temporal_block `1year`) <sup>2</sup>.
    - Additionally, the `dynamic_unit/connection...indices` functions receive an extra temporal_block argument, with the default being `anything` -> meaning that all timeslices (representative *and* non-representative) are being called (the problematic with this is explained further below)
- `add_variable!` function:
    - the generation of variables (and variable references) remains the same (keeping in mind that this function calls the default `variable_indices` function, which defaults to the representative indices)
    - additionally a mapping is performed from the non-representative timeslices to the representative timeslice through adding these variable references to `m.[:ext][:variables]` dictionaries. This mapping uses the above mentioned `ordering_periods` parameter <sup>3</sup>
    - that means that the key of a non-representative variable index points to it's corresponding representative variable
- Constraints:
    - most constraints remain untouched, and are just generated for each representative day
    - exceptions:
        - `node_injection_constraint`: Here, the node_state variable comes into play, which we want to track for the whole non-representative period (e.g. `1year`). The constraint is thus generated for the whole (non-representative) period. Note that, the non-representative indices of e.g. the `unit_flow` will point to the corresponding representative day variable.
        - Other dynamic constraints: If we were to use only the representative indices for  e.g. the `constraint_minimum_down_time`, we would not take into account the sequence of the representative days (coming from the ordering periods). This is why, at the moment, each dynamic constraint is generated for each timestep of the year. However, especially these constraints are rather expensive. Thus it would be nice to e.g. only include these constraints once per representative day sequence` <sup>4</sup>, or accept inaccuracies. Simplification can be made as follows:
        - we enforce this constraint only on the representative day in it's sequence in the year (itself), taking as history the mapping of the day that comes histrically before the representative day. e.g.: Day 5 is a representative day, Day 4 is non-representative and maps to Day 7. Dynamic constraints are generated on Day 5, looking into the past of -> representative Day 7. 
        - moreover, the dynamic constraints at the are causing problems as the history of a non-representative day for the model_start is not defined
---
 <sup>2</sup> We should probably add an additional method parameter, to make it clearer.
Node_state:
<sup>3</sup> To save guard this in the future, we should probably add a relationship between the non-representative and representative temporal_blocks, in case we would have more than 1 "ordering" temporal_block. (todo)
<sup>4</sup> This "rep. day sequence" sounds easier than it, as it does not necessarily only include the sequence of 2 rep.days, but possibly more.

**Comment by manuelma** [comment]
> indices function do now have a temporal_block keyword

I suppose this argument is used to filter the time slices in the result? So if some temporal blocks are given, only indices where the time slice belongs in those temporal blocks are returned?

> The default for this temporal_block argument is setdiff(temporal_block(), indices(ordering_periods)), meaning that the default for the indices functions are the representative indices

Ok, so `indices(ordering_periods)` yields temporal blocks that have `ordering_periods` different than `nothing`. Those are the temporal blocks whose time slices should be mapped to a representative period, right? And by taking the difference between all temporal blocks and those that should be mapped, you get those that *shouldn't* be mapped. And that's your default?

I think I follow the reasoning, and it looks like we can preprocess something to make it more explicit.

I still need to read what follows, these are just some initial comments.
