### ISSUE TITLE
objective values (costs) as per temporal block resolution

### ISSUE THREAD

**Issue by nnhjy** [Spine-project/SpineOpt.jl#341]
Thanks to the method proposed in [issue 313](https://github.com/Spine-project/SpineOpt.jl/issues/313), `SpineOpt` can record the objective values per optimisation window. 

Maybe it's time now to refine the objective value recording process so as to report the values with respect to the resolution of the designated temporal block(s)?

**Comment by mihlema** [comment]
(merged this into #313 for conciseness)
