### ISSUE TITLE
Ramping restrictions of unit connected to multiple nodes

### ISSUE THREAD

**Issue by KristofPhillips95** [Spine-project/SpineOpt.jl#344]
When a unit is connected to multiple nodes (of the same commodity) ramping restrictions can be defined for the unit as a whole, by defining a node group that contains both nodes. Currently, the ramping does not get netted out over the two nodes, I was wondering if this is something that we want? 

An example would be the following: 

node 1: demand [100 130]
node 2: demand [120 100]

When a unit is now connected to both nodes it will have a ramp_up with 30 and ramp_down with 20 between the first and second timestep. Perhaps it can make sense to calculate a netto ramping first, so that the unit only has to ramp_up with 10. 

Any thoughts?

**Comment by DillonJ** [comment]
Interesting - out of curiosity - what is the use-case here?

When you create the two two nodes and the corresponding unit relationships - you create independent flow variables between the unit and the nodes in question. These flow variables aren't dimensioned by commodity so the fact that they are connected to the same commodity is really irrelevant in this respect. 

I don't clearly see why we would want to net this ramping if we have explicitly created the two nodes, each with their own demands.

**Comment by KristofPhillips95** [comment]
Well that is more or less what I was wondering as well, it came to my attention that it works this way and I was wondering if there is a use case in which this could become important. 

That being said, I do feel that it matters if it is the same commodity or not. If it is not, the netting wouldn't make sense for sure. However, if a unit is delivering the same commodity to two nodes, it would seem to me like netting makes sense because the actual amount that the unit has to deliver of said commodity will be the sum of the unit flows to the two individual nodes. 

But maybe it does indeed not make sense to define multiple nodes in that case.

**Comment by mihlema** [comment]
@KristofPhillips95 thanks again for pointing this out. It seems that current functionality is not conflicting with existing use cases. I'll close this issue for now - reopen if necessary
