### ISSUE TITLE
`connection_flow` or `connection_intact_flow`?

### ISSUE THREAD

**Issue by manuelma** [Spine-project/SpineOpt.jl#345]
I have been tricked multiple times by this. It seems that if no investments, `connection_flow` has no actual meaning, and one needs to look at `connection_intact_flow`?

Another related question is, connection investments only work for the PTDF model? That is, one cannot study investments in connections using the 'normal' transport flow model?

**Comment by mihlema** [comment]
I was wondering the same thing. I think we should be very careful here, not to impair our core elements here.
@DillonJ ?

**Comment by DillonJ** [comment]
Unless I'm mistaken - in the case of no investments, connection_flow = connection_intact_flow. The way to think of it is, that we have a new variable to represent ptdf-based flow which is useful for a number of reasons. 

In the current implementation, If you have ptdf based flow defined for a network, you can't have normal transport flow for a subset of lines in that network. This is how it was before investments. We discussed this before and a workaround at the moment, is to use units if you want to implement a DC line within a ptdf network - this extends also to investments - if you want a normal transport based connection investment, this is the way to do it also. So the investment functionality is consistent. I don't believe it impairs the core functionality in that none of this is relevant if you are using ptdfs.

**Comment by DillonJ** [comment]
>That is, one cannot study investments in connections using the 'normal' transport flow model?
If you are not using PTDFs, nothing should have changed - normal transport flow on connections and normal transport based connection investments with full decomposition support. That was the intention in any case - are you finding otherwise? 

The only limitation is that you can't have a transport based investment on a line that has ptdf flow - that doesn't make much sense in any case.

**Comment by manuelma** [comment]
What I have observed is, if using PTDF without investments, connection_flow seems to lose meaning somehow, and it takes either the value of 0 or the line capacity with a pattern that I wasn't able to explain. But it's definitely different than connection_intact_flow which takes the 'right' value so to say.

So I need to investigate more. I'm sure it's easy to solve.

**Comment by manuelma** [comment]
So I checked, and if no candidate connections, the constraint (...connection_flow_intact_flow) is not being written. The problem seems to be in the indices function, where there's a loop over candidate connections at top-level. I think I can fix this.

I also see a typo (`cadidate_connection` instead of `is_candidate`) and a bad call to `Iterators.flatten` where the inner iterators are not well 'aligned'. It looks like our unit-tests are passing anyways despite this fact.

**Comment by mihlema** [comment]
@manuelma I didn't follow up on this one. Is this working now?

**Comment by manuelma** [comment]
It works well at the moment. We fixed the constraint indices function.
