### ISSUE TITLE
Allocation concept reference

### ISSUE THREAD

**Issue by mihlema** [Spine-project/SpineOpt.jl#346]
Our concept reference chapter needs to be extended to hold a description of each and every concept. As discussed during our last call, I tried to allocate different concept reference chapters. It is not necessarily straightforward, so please feel free to reach out or swap the allocations. Also, if you feel there should be others included/excluded, do let me know.
For each concept entry, one needs to create an `*.md` file with the exact name of the concept. As an example, @Tasqu has created e.g. `concept_reference/stochastic_structure.md`. Once a concept file is created and written we can tick the box here :raised_hands:.

 - [x] report,@nnhjy
 - [x] output,@nnhjy
 - [x] model,@mihlema
 - [x] stochastic_structure,@Tasqu
 - [x] unit_constraint,@nnhjy
 - [x] temporal_block,@KristofPhillips95
 - [x] commodity,@mihlema
 - [x] stochastic_scenario,@Tasqu
 - [x] node,@Tasqu
 - [x] unit,@manuelma
 - [x] connection,@manuelma
 - [x] max_gap,@DillonJ
 - [x] start_up_cost,@TimMertens
 - [x] max_iterations,@DillonJ
 - [x] candidate_storages,@DillonJ
 - [x] fix_ratio_out_in_unit_flow,@mihlema
 - [x] max_units_on_coefficient_out_out,@nnhjy
 - [x] max_res_shutdown_ramp,@mihlema
 - [x] res_start_up_cost,@TimMertens
 - [x] commodity_lodf_tolerance,@manuelma
 - [x] min_ratio_out_in_connection_flow,@mihlema
 - [x] fix_shut_down_unit_flow,@mihlema
 - [x] node_state_coefficient,@Tasqu
 - [x] ramp_up_costs,@TimMertens
 - [x] block_end,@KristofPhillips95
 - [x] node_state_min,@Tasqu
 - [x] connection_investment_lifetime,@manuelma
 - [x] ramp_up_limit,@KristofPhillips95
 - [x] minimum_reserve_activation_time,@mihlema
 - [x] write_mps_file,@DillonJ  (Should this be moved to the report object instead of the model object?)
 - [x] curtailment_cost,@TimMertens
 - [x] min_ratio_in_out_unit_flow,@mihlema
 - [x] min_res_shutdown_ramp,@mihlema
 - [x] min_ratio_in_in_unit_flow,@mihlema
 - [x] max_ratio_in_in_unit_flow,@mihlema
 - [x] unit_incremental_heat_rate,@DillonJ
 - [x] connection_conv_cap_to_flow,@mihlema
 - [x] fix_units_on_coefficient_in_in,@nnhjy
 - [x] fix_nonspin_ramp_up_unit_flow,@KristofPhillips95
 - [x] fix_units_on_coefficient_in_out,@nnhjy
 - [x] connection_investment_cost,@TimMertens
 - [x] fix_connection_intact_flow,@manuelma (needed? see #351 )
 - [x] fix_nonspin_units_started_up,@KristofPhillips95
 - [x] upward_reserve,@mihlema
 - [x] weight,@KristofPhillips95
 - [x] online_variable_type,@KristofPhillips95
 - [x] min_down_time,@KristofPhillips95
 - [x] max_ratio_out_out_unit_flow,@mihlema
 - [x] fix_ramp_down_unit_flow,@KristofPhillips95
 - [x] fix_units_on_coefficient_out_out,@nnhjy
 - [x] ~~graph_view_position,@manuelma~~ (irrelevant for SpineOpt)
 - [x] max_units_on_coefficient_in_in,@nnhjy
 - [x] ~~connection_resistance,@manuelma~~ (not in use at the moment)
 - [x] ~~write_ptdf_file,@manuelma (Should this be moved to the report object instead of the model object?)~~ (not in use at the moment)
 - [x] unit_capacity,@mihlema
 - [x] nodal_balance_sense,@manuelma
 - [x] unit_start_flow,@DillonJ
 - [x] commodity_ptdf_threshold,@manuelma
 - [x] roll_forward,@KristofPhillips95
 - [x] fix_storages_invested_available,@DillonJ
 - [x] ramp_down_costs,@TimMertens
 - [x] right_hand_side,@DillonJ
 - [x] max_res_startup_ramp,@mihlema
 - [x] min_units_on_coefficient_out_out,@nnhjy
 - [x] fuel_cost,@TimMertens
 - [x] fix_ratio_out_out_unit_flow,@mihlema
 - [x] tax_out_unit_flow,@TimMertens
 - [x] downward_reserve,@mihlema
 - [x] fix_connections_invested,@manuelma (needed? see #351 )
 - [x] units_on_coefficient,@nnhjy
 - [x] fix_unit_flow_op,@DillonJ
 - [x] vom_cost,@TimMertens
 - [x] fix_units_on_coefficient_out_in,@nnhjy
 - [x] frac_state_loss,@Tasqu
 - [x] fix_units_invested_available,@DillonJ
 - [x] tax_net_unit_flow,@mihlema
 - [x] demand,@nnhjy
 - [x] unit_investment_variable_type,@DillonJ
 - [x] block_start,@KristofPhillips95
 - [x] fix_ratio_out_in_connection_flow,@mihlema
 - [x] number_of_units,@KristofPhillips95
 - [x] node_slack_penalty,@DillonJ
 - [x] unit_availability_factor,@mihlema
 - [x] ramp_down_cost,@TimMertens
 - [x] ramp_up_cost,@TimMertens
 - [x] fix_connections_invested_available,@manuelma
 - [x] constraint_sense,@manuelma
 - [x] connection_availability_factor,@mihlema
 - [x] balance_type,@manuelma
 - [x] candidate_connections,@manuelma
 - [x] minimum_operating_point,@KristofPhillips95
 - [x] fix_nonspin_units_starting_up,@KristofPhillips95
 - [x] reserve_procurement_cost,@TimMertens
 - [x] min_shutdown_ramp,@KristofPhillips95
 - [x] max_units_on_coefficient_out_in,@nnhjy
 - [x] storage_investment_lifetime,@DillonJ
 - [x] min_units_on_coefficient_in_in,@nnhjy
 - [x] has_state,@Tasqu
 - [x] diff_coeff,@Tasqu
 - [x] tax_in_unit_flow,@mihlema
 - [x] is_active,@DillonJ
 - [x] max_startup_ramp,@KristofPhillips95
 - [x] weight_relative_to_parents,@Tasqu
 - [x] fix_units_on,@KristofPhillips95
 - [x] ~~write_lodf_file,@manuelma  (Should this be moved to the report object instead of the model object?)~~ (not in use at the moment)
 - [x] storage_investment_variable_type,@DillonJ
 - [x] min_units_on_coefficient_in_out,@nnhjy
 - [x] fix_nonspin_ramp_down_unit_flow,@KristofPhillips95
 - [x] node_state_cap,@Tasqu
 - [x] units_started_up_coefficient,@nnhjy
 - [x] shut_down_cost,@TimMertens
 - [x] connection_flow_delay,@manuelma
 - [x] unit_investment_cost,@TimMertens
 - [x] model_start,@mihlema
 - [x] resolution,@KristofPhillips95
 - [x] connection_emergency_capacity,@manuelma
 - [x] max_shutdown_ramp,@KristofPhillips95
 - [x] max_cum_in_unit_flow_bound,@mihlema
 - [x] fix_unit_flow,@mihlema
 - [x] fix_node_state,@Tasqu
 - [x] fix_units_invested,@DillonJ
 - [x] candidate_units,@DillonJ
 - [x] fix_ratio_in_out_unit_flow,@mihlema
 - [x] fix_storages_invested,@DillonJ
 - [x] model_type,@DillonJ
 - [x] representative_periods_mapping,@mihlema
 - [x] unit_investment_lifetime,@DillonJ
 - [x] max_ratio_in_out_unit_flow,@mihlema
 - [x] min_ratio_out_out_unit_flow,@mihlema
 - [x] max_ratio_out_in_connection_flow,@mihlema
 - [x] connection_investment_variable_type,@manuelma
 - [x] storage_investment_cost,@TimMertens
 - [x] fix_start_up_unit_flow,@mihlema
 - [x] output_db_url,@manuelma
 - [x] fom_cost,@TimMertens
 - [x] operating_points,@DillonJ
 - [x] model_end,@KristofPhillips95
 - [x] unit_flow_coefficient,@nnhjy
 - [x] connection_monitored,@DillonJ
 - [x] min_up_time,@KristofPhillips95
 - [x] max_ratio_out_in_unit_flow,@mihlema
 - [x] fractional_demand,@manuelma
 - [x] stochastic_scenario_end,@Tasqu
 - [x] connection_capacity,@DillonJ
 - [x] commodity_physics,@DillonJ
 - [x] min_res_startup_ramp,@mihlema
 - [x] connection_flow_coefficient,@nnhjy
 - [x] connection_flow_cost,@TimMertens
 - [x] min_startup_ramp,@KristofPhillips95
 - [x] fix_connection_flow,@manuelma
 - [x] operating_cost,@TimMertens
 - [x] fix_ratio_in_in_unit_flow,@mihlema
 - [x] fix_nonspin_units_shut_down,@KristofPhillips95
 - [x] duration_unit,@manuelma
 - [x] ramp_down_limit,@KristofPhillips95
 - [x] node_opf_type,@DillonJ
 - [x] min_ratio_out_in_unit_flow,@mihlema
 - [x] connection_type,@DillonJ
 - [x] connection_reactance,@DillonJ
 - [x] unit_idle_heat_rate,@DillonJ
 - [x] fix_ramp_up_unit_flow,@KristofPhillips95
 - [x] unit_conv_cap_to_flow,@KristofPhillips95
 - [x] max_units_on_coefficient_in_out,@nnhjy
 - [x] min_units_on_coefficient_out_in,@nnhjy
 - [x] state_coeff,@Tasqu
 - [x] connection_contingency,@DillonJ
 - [x] is_reserve_node,@mihlema
 - [x] demand_coefficient,@nnhjy
 - [x] connection_type_list,@DillonJ
 - [x] constraint_sense_list,@manuelma
 - [x] model_type_list,@DillonJ
 - [x] variable_type_list,@manuelma
 - [x] balance_type_list,@manuelma
 - [x] node_opf_type_list,@manuelma
 - [x] write_mps_file_list,@DillonJ  (Should this be moved to the report object instead of the model object?)
 - [x] duration_unit_list,@manuelma
 - [x] commodity_physics_list,@DillonJ
 - [x] unit_online_variable_type_list,@KristofPhillips95
 - [x] connection_investment_variable_type_list,@manuelma
 - [x] unit_investment_variable_type_list,@DillonJ
 - [x] boolean_value_list,@TimMertens
 - [x] model__temporal_block,@KristofPhillips95
 - [x] node__node,@Tasqu
 - [x] connection__node__node,@DillonJ
 - [x] connection__to_node,@DillonJ
 - [x] unit__from_node__unit_constraint,@DillonJ
 - [x] model__stochastic_structure,@Tasqu
 - [x] node__investment_temporal_block,@DillonJ
 - [x] node__stochastic_structure,@Tasqu
 - [x] units_on__stochastic_structure,@Tasqu
 - [x] parent_stochastic_scenario__child_stochastic_scenario,@Tasqu
 - [x] model__default_investment_temporal_block,@DillonJ
 - [x] connection__to_node__unit_constraint,@DillonJ
 - [x] model__default_stochastic_structure,@Tasqu
 - [x] connection__from_node__unit_constraint,@DillonJ
 - [x] unit__investment_temporal_block,@DillonJ
 - [x] unit__node__node,@mihlema
 - [x] unit__unit_constraint,@DillonJ
 - [x] unit__to_node,@mihlema
 - [x] units_on__temporal_block,@KristofPhillips95
 - [x] unit__investment_stochastic_structure,@manuelma
 - [x] model__default_temporal_block,@KristofPhillips95
 - [x] unit__commodity,@mihlema
 - [x] node__temporal_block,@KristofPhillips95
 - [x] connection__investment_stochastic_structure,@manuelma
 - [x] unit__from_node,@mihlema
 - [x] node__commodity,@DillonJ
 - [x] stochastic_structure__stochastic_scenario,@Tasqu
 - [x] model__report,@nnhjy
 - [x] connection__from_node,@DillonJ
 - [x] report__output,@nnhjy
 - [x] unit__to_node__unit_constraint,@DillonJ
 - [x] connection__investment_temporal_block,@manuelma
 - [x] node__investment_stochastic_structure,@Tasqu
 - [x] node__unit_constraint,@DillonJ
 - [x] model__default_investment_stochastic_structure,@Tasqu

**Comment by Tasqu** [comment]
Closing this issue. I wrote all the remaining missing descriptions  so that my auto-generation code no longer throws errors related to that.
