### ISSUE TITLE
Do we need a `fix_{variable_value}` parameter for each variable?

### ISSUE THREAD

**Issue by manuelma** [Spine-project/SpineOpt.jl#351]
Seems there just for consistency, but I don't think it's useful in practice. I'm trying to imagine a case where a user wants to fix the flow on a connection *before* any investments. To me, `connection_intact_flow` is a model artifact, needed to write the investment constraints, and the user shouldn't be too concerned with it.

Thoughts? Is it ok if I just get rid of it? @mihlema @DillonJ 

**Edit**: In other words, I think `fix_connection_flow` is all that a user wants.

**Comment by DillonJ** [comment]
We don't need or use it right now - but I guess from a consistency point of view, this is the mechanism we use to fix variables when desired. Is there a performance impact? I suppose it could be re-introduced at a future time if needed.

However, I can see use cases for it. For example - say there is some sort of constraint, that if the line is built, there is some fixed flow on the line - but if it's not built then this flow is not imposed - then it could be useful.

I guess it has as many potential uses and non-uses as any other fix-variable

**Comment by manuelma** [comment]
> Is there a performance impact?

There is, even if it the value is not set in the db. I guess we could add a condition to minimize that impact...

> I guess it has as many potential uses and non-uses as any other fix-variable

I don't agree with this. `fix_unit_flow`, for instance, feels much more practical.

> For example - say there is some sort of constraint, that if the line is built, there is some fixed flow on the line - but if it's not built then this flow is not imposed - then it could be useful.

This is certainly true, but the question is, why? Why would there be such a constraint in practice?

I guess what I would like is make the distinction between variables in terms of whether or not they are somehow 'internal' to the model. Perhaps that's a bit arbitrary, but take for instance `node_injection`. We don't have `fix_node_injection` and that makes sense, because it's an artifact, just a helper to write better constraint code. And what I'm arguing is `fix_connection_intact_flow` is the same in this respect...

**Comment by DillonJ** [comment]
If we think that fixing the flow on a line is something we might want to do, then it is not a stretch to think that we would want to fix the flow on a candidate line but only if it is built, which is what `fix_connection_intact_flow` allows you to do.

I don't feel that strongly about it though - we can always re-introduce it down the line if someone wants it?

**Comment by manuelma** [comment]
> fix the flow on a candidate line but only if it is built

Thanks for the explanation! Maybe I'm missing something, but can't this flow be fixed via `fix_connection_flow`?

**Comment by manuelma** [comment]
The same happens for `fix_connections_invested`. Isn't it more reasonable to just use `fix_connections_invested_available`?

- We don't have `fix_connections_decomissioned`
- For analogy with simple commitment units, we don't have `fix_units_started_up`.

**Comment by DillonJ** [comment]
Regarding `fix_*_invested` and `fix_*_invested_available` - it depends on whether or not you want to fix the point in time investment decision, or if you want to specify that a candidate unit/connection exists at a certain time or not - I can see use cases for both. So if you're asking if there is utility - I think there is - but can we get rid of them? That's another question. I don't feel strongly about it. My inclination is to think that they're there - so leave them - but if there is a significant performance hit and you want to get rid of them - that's could be ok. Bear in mind that decomposition uses some of these `fix_*` parameters  - having  them also leaves the door open for future functionalities if needed - I.e. a generic way to fix the value of whatever variable should we ever need it. But again, they can be introduced whenever such need arises.

**Comment by manuelma** [comment]
Thanks, @DillonJ, some comments below

> But again, they can be introduced whenever such need arises

This is an important point for me. It's so easy to add them later.

But the most important point is consistency, it's either all or nothing. If we had `fix_connections_decommissioned`, `fix_units_started_up`, `fix_node_injection`, I wouldn't mind keep them all. So for me, we either add the ones that are missing and deal with the performance blow, or just keep a subset of the *reasonable* ones.

**Comment by DillonJ** [comment]
@manuelma I presume you've looked at which ones are used in the decomposition code?

**Comment by manuelma** [comment]
> @manuelma I presume you've looked at which ones are used in the decomposition code?

I'm searching the entire `src` folder for usages. So I noticed that `fix_connections_invested_available` it's only used in the variable creation, not in any other parts of the code.

**Comment by mihlema** [comment]
The slimmer the better I'd say when it comes to the fixed parameter values - unless they are supposed to be actively used somewhere.

**Comment by mihlema** [comment]
Maybe we can close this issue for now. Reopen if necessary
