### ISSUE TITLE
What's the purpose of `add_constraint_cyclic_node_state`?

### ISSUE THREAD

**Issue by manuelma** [Spine-project/SpineOpt.jl#354]
It's never called, and there's a comparison against `:value_true`. It is added by 40dc8cb7e92d187db1b00b547725b6497580c14e

Do we need it? Can we get rid of it @mihlema ?

**Comment by mihlema** [comment]
Yes, I also realized this then working on the gas study, that cyclic node state was not at all included anywhere. 
In the new merge request, it is updated to be compatible with the master and included in `run_spineopt` + tests. (The `:value_true` is also gone)

**Comment by manuelma** [comment]
I guess it's covered by that PR then. Good!
