### ISSUE TITLE
Does the taxes cost term have the right summands?

### ISSUE THREAD

**Issue by TimMertens** [Spine-project/SpineOpt.jl#357]
The final summation in the taxes cost term (i.e., the one containing p_(tax_in_unit_flow)) has a summand for n ∈ ind(p_(tax_out_unit_flow)). I would assume this to be for n ∈ ind(p_(tax_in_unit_flow)). 

Could this be a typo in the code?

**Comment by mihlema** [comment]
Good catch; I just fixed the typo
