### ISSUE TITLE
Use `big_m` consistently

### ISSUE THREAD

**Issue by manuelma** [Spine-project/SpineOpt.jl#360]
Recently a parameter called `big_m` has been introduced. We also have the constant `10000` in `candidate_connection_flow_lb`. Do we need to homogenize the usage of `big_m` broadly?

Cc @DillonJ @mihlema

**Comment by DillonJ** [comment]
I  think it's a good idea to use it where possible and this is a good example where we can use it

**Comment by manuelma** [comment]
maybe the default value should be 10000? At the moment is `nothing`

**Comment by mihlema** [comment]
I think either is fine, but from what I know about `big_m` is that is really dependent on the problem at hand and often requires some finesse. I feel like this should be a conscious decision of the modeler, as there is not such `big_m` to rule them all.

**Comment by mihlema** [comment]
@manuelma WDYT how we should proceed here? Personally I rather would get an error when not consciously defining my `big_m` - so it doesn't just assign an (unintentional) value for me. But I'm also fine with the other option
