### ISSUE TITLE
Getting rid of operating costs?

### ISSUE THREAD

**Issue by mihlema** [Spine-project/SpineOpt.jl#362]
Currently, we have in our objective
:variable_om_costs,`
`:fixed_om_costs,`
`:operating_costs,`
`:fuel_costs,`

as @TimMertens pointed out,  `:operating_costs,` seems a bit superfluous. Does anyone use it at the moment? Otherwise I'd suggest to get rid of it - and use the other cost terms. WDYT?

**Comment by manuelma** [comment]
I agree 100 percent.
