### ISSUE TITLE
Known concept reference auto-generation bugs.

### ISSUE THREAD

**Issue by Tasqu** [Spine-project/SpineOpt.jl#371]
While working on the documentation deliverable, I noticed a couple of bugs still lingering in the concept reference section auto-generation code.

1. `graph_view_position` only lists related relationship classes, even though it's also an object class parameter. Something still seems to get overlooked when cross-referencing the concepts.
2. `Parameter value lists` aren't handled correctly. I've used the `default_value` field for collecting the potential values listed in the template, even though there's no "default value" for a parameter value list. Instead, I think we'll need to add a new field in the `concept dictionary` to collect potential values for parameter value lists.

**Comment by mihlema** [comment]
@Tasqu I think this is not very pressing, but I guess you'd be the expert, whenever we want to improve this

**Comment by Tasqu** [comment]
Closing this issue. As far as I could tell, I managed to fix these issues *without* messing up the rest of the concept reference while doing so.

We can always make new issues if we find more problems with the concept reference autogeneration.
