### ISSUE TITLE
Benders treatment of units is somewhat special

### ISSUE THREAD

**Issue by manuelma** [Spine-project/SpineOpt.jl#375]
I couldn't find a reason for this, so I'm asking.

In the benders implementation for connection investments, we obtain the marginal value for the `connections_invested_available` variable by looking at `bound_connections_invested_available`. The same goes for storage (just replace `connections` with `storages` in the previous sentence).

However, units work differently for some reason. The marginal value we calculate is for `units_available`, and we do it by looking at `bound_units_on`. This feels like a mistake, but I can't tell for sure.

@DillonJ what am I missing?

**Comment by mihlema** [comment]
I think I remember vaguely it had to do with the duals of the `units_on` constraint being zero..? @DillonJ you probably know better

**Comment by manuelma** [comment]
> this was intentional and is because of the relationship between units_on and units_invested_available via constraints constraint_units_on and constraint_units_available Essentially, when we fix units_invested_available, we are also setting the upper bound on units_on and it is then effectively the marginal value of this upper bound constraint that represents the marginal value of this unit in this timestep

By @DillonJ on slack. So it's good, we can close this now.
