### ISSUE TITLE
Units with ramp_down_limit can never shutdown

### ISSUE THREAD

**Issue by manuelma** [Spine-project/SpineOpt.jl#385]
The ramp_down constraint looks something like this:

`ramp_down_flow <= (units_on - units_shutdown) * ramp_down_limit * capacity`

When the unit is shutting down, we have `units_on = 0` and `units_shutdown = 1` which results then in `ramp_down_flow <= something negative`, so the unit can never shutdown.

I believe the solution would be simply `ramp_down_flow <= units_on * ramp_down_limit * capacity` because `units_shutdown = 1` already implies `units_on = 0`. So we have `ramp_down_flow = 0` when the unit is shutting down, as expected (and `shutdown_flow` becomes different than 0).

@mihlema is my fix correct?

**Comment by manuelma** [comment]
I just went ahead and implemented my fix. Hope it's good, it makes sense to me.

There was another problem. `shutdown_flow` variables were only generated if `max_shutdown_ramp` was defined. But we also need them if `ramp_down_limit` is specified, because of `constraint_split_ramps`.

**Comment by mihlema** [comment]
(from slack discussion) This bug sneaked in overtime. It should be `units_on - `units_started_up` , so that only online units are considered (not the ones just starting up or shutting down). For start/shutdown ramps, the `max_shut_down_ramp` etc. constraints are responsible.

**Comment by manuelma** [comment]
Thanks @mihlema it's implemented now as you suggest. I think it works nicely,
