### ISSUE TITLE
Getting (partly) rid of `number_of_units`?

### ISSUE THREAD

**Issue by mihlema** [Spine-project/SpineOpt.jl#387]
I feel like we have a kind of double standard when it comes to `number_of_units` vs. `fix_units_invested`/`fix_units_invested_available`. Some constraints, e.g. `constraint_units_available` would become a bit cleaner if we would only have `units_invested_available`. 

I think it'd still be nice for the user to be able to define `number_of_units` in the db, but I think we could interpret `number_of_units` as `fix_units_invested`  for the timestep just before the model start. Then also the originally installed units will not necessarily stay in the model forever, but only for their lifetime (if specified).

Alternatively, we could simply replace `fix_units_invested_available` with `number_of_units` completely, to ensure consistency.

**Comment by jkiviluo** [comment]
Not sure how to do this in SpineOpt, but FlexTool I've made a distinction between 'existing' units and 'invest_forced' units. The difference is that the results will not include investment costs from existing units but they will from units that have a forced investment. This can be helpful in analysing scenarios. Then there is also a parameter for 'invest_max'. 

The parameter name does not contain 'unit', since it's a parameter for units.

**Comment by DillonJ** [comment]
I agree with Juha that we should make the distinction between units that pre-exist before the model starts and forced investments. For example, if we have `number_of_units` = 4 and `candidate_units` = 1 and then `fix_units_invested` = 1, this would allow you to see the marginal value of the new investment unit because the 5th unit it is an investment decision. This wouldn't be possible with `number_of_units` = 5

**Comment by mihlema** [comment]
>Not sure how to do this in SpineOpt, but in FlexTool I've made a distinction between 'existing' units and 'invest_forced' units. The difference is that the results will not include investment costs from existing units but they will from units that have a forced investment. This can be helpful in analysing scenarios. Then there is also a parameter for 'invest_max', that allows the model to choose how much to invest (within the limit of course).

As the `fix_units_invested_available` would happen before the start of the model, the investment costs should not be seen in the model - for forced investments within the model horizon, the investment costs will appear.

>I agree with Juha that we should make the distinction between units that pre-exist before the model starts and forced investments. For example, if we have number_of_units = 4 and candidate_units = 1 and then fix_units_invested = 1, this would allow you to see the marginal value of the new investment unit because the 5th unit it is an investment decision. This wouldn't be possible with number_of_units = 5

I am not quite sure if this would work Jody. As you are fixing the variable, it will appear as a constant and hence, to the optimization, there will be no difference between 4+1 and 5 (for e.g. the `constraint_units_available`.

But maybe I should motivate this proposed change a bit more:
- Currently, whatever `number_of_units` are given at the start of the optimization will remain in the system until infinity. @jkiviluo for your proposed `existing` units, I think this would already not be the desired behaviour. To phase them out after their lifetime, we do need to know their vintage year - we could either duplicate lifetime constraints also for `number_of_units` or as proposed, we just translate them into `units_invested` (before the start of the optimization` and don't have to repeat any of the constraints
- The vintage year, and lifetime, is also again required for cost terms such as the fixed operational costs. 
- Also with `number_of_units` being always in the system, it would not be possible to include degradation of units of time in the longs run
- Just FYI, the current units availability constraint looks like this:
 ``` 
units_available[u, s, t]
            ==
            + unit_availability_factor[(unit=u, stochastic_scenario=s, analysis_time=t0, t=t)] * (
                + number_of_units[(unit=u, stochastic_scenario=s, analysis_time=t0, t=t)] + expr_sum(
                    units_invested_available[u, s, t1] for (u, s, t1) in units_invested_available_indices(
                        m;
                        unit=u,
                        stochastic_scenario=s,
                        t=t_in_t(m; t_short=t),
                    );
                    init=0,
                )
            )
```

I am also open to other suggestions, but I think it's not really nice to having to repeat e.g. the `unit_lifetime` constraint for `number_of_units` as they really essentially are investments made before the model begins

**Comment by DillonJ** [comment]
@mihlema A fixed variable isn't the same as a constant - it's a variable which has its upper and lower bounds set to the same value and this bound constraint has a marginal value.

**Comment by mihlema** [comment]
I belive the issue can be closed, I think there's another way around for the #326 without getting rid of number_of_units. Closing this issue
