### ISSUE TITLE
Extend unit constraint to include investment variables

### ISSUE THREAD

**Issue by CIODWYER** [Spine-project/SpineOpt.jl#390]
For storage, it would be good if a unit capacity could be linked to node_state_cap e.g. may want to included standard investment options for batteries which have different durations rather than independently investing in power and energy capacity

**Comment by mihlema** [comment]
@DillonJ I guess you're the expert ;)

**Comment by mihlema** [comment]
Is realistic to include this now? Otherwise I believe we should have a roadmap issue for user-constraint requirements in general (ramping variables, investment variables, we could also think of pressure, voltage angle etc...)

**Comment by DillonJ** [comment]
I will do this at the same time as renaming unit__constraint to user__constraint... I'll crunch it!

**Comment by DillonJ** [comment]
This has been done in the commit above. Additional tests have been implemented and the docs have been updated.
