### ISSUE TITLE
Native is_active functionality

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/SpineOpt.jl#392]
We have discussed this issue many times in the past including on a recent SpineOpt call.

We need the functionality to quickly and easily deactivate objects in a model so they don't form part of the optimisation problem. 

This functionality needs to work with scenarios and alternatives, so , for example, a particular object may be active in one scenario and not active in another.

This is currently possible with the tool - feature - method system but some had the feeling that this was a little too cumbersome. Also, it is not documented and there is some uncertainty regarding whether or not it is working properly. There is also the issue that the current implementation does not work nicely if you are running SpineOpt from a script rather than from within toolbox.

I propose that our first step should be to get our heads around the existing implementation and 
 - establish how it is supposed to work
 - test if it is working as expected
 - add / document the functionality to utilise from within a Julia script 
 - document the functionality
 - make improvements
 - extend the functionality

@manuelma I wonder could you explain briefly here how the current `is_active` functionality is supposed to work using tool filters. I can then test and then we can discuss next steps?

**Comment by DillonJ** [comment]
Actually - removing relationships via the context menu doesn't appear to be working very well at all. Even removing one relationship will just remove the name but leave the icon and the commit button is greyed out

**Comment by DillonJ** [comment]
Update :
So I've been testing this and I 

```
ERROR: LoadError: No model of type spineopt_operations defined
.......
```
The model runs fine without the is_active tool filter enabled so this suggests to me that it is somehow interfering with default parameter values (since `spineopt_operations` is the default for the parameter concerned here.

Thoughts @manuelma

**Comment by manuelma** [comment]
Great! Can you share your db so I can test it myself?

**Comment by DillonJ** [comment]
Actually - more testing - when I set is_active is true for the model object, that specific error goes away, but there are more...

I was hoping that by having a default value of true for the is_active parameter, then by default, all objects are included unless explicitly excluded by setting is_active=false.

So it seems like the default value of is_active isn't being processed? Perhaps parameter defaults aren't considered at Toolbox level and this is the issue?

**Comment by manuelma** [comment]
Superseded by https://github.com/Spine-project/Spine-Toolbox/issues/1513
