### ISSUE TITLE
Problem with representative periods and renewable generation 

### ISSUE THREAD

**Issue by CIODWYER** [Spine-project/SpineOpt.jl#398]
When using representative periods unit flow for wind is always 0 for the first hour of each representative period. This happens for both investment units and existing units which are both set up with. Using the same database for unit commitment does not have the same problem. It's probably happening for all units with unit_availability_factor but PV always 0 at midnight anyway

**Comment by DillonJ** [comment]
Hi folks - @manuelma @mihlema do you have any suspicions regarding what might be happening here? It would be great to knock this one on the head asap. I have a feeling it's something to do with temporals and ordered rep days .

**Comment by manuelma** [comment]
No idea but it would be good to reproduce with the smallest dataset possible. Otherwise we can look at the code and try to figure out if there's any special boundary condition.

**Comment by CIODWYER** [comment]
I'm in a meeting now but I will put together a simple dataset a.s.a.p

**Comment by mihlema** [comment]
This issue originated from the issue #221.
The following fixes are proposed:
- either connect all representative nodes, to also the block of non-representative periods. For the future, we should have a handle to differentiate between short term and long term storages (at the moment, all are treated as possible long-term storages; i.e. the nodal_balance is generated for every period (non-/representative).
- If representative days without ordering are used, we could re-introduce "bridging the gap" between two disconnected periods

**Comment by mihlema** [comment]
(Discussion continued in #221; closing this issue)
