### ISSUE TITLE
Small bug in variable_common.jl

### ISSUE THREAD

**Issue by trusl** [Spine-project/SpineOpt.jl#4]
There seems to be a minor bug in the create_variable function where both upper and lower bound is set equal to lb. Unsure whether this has a major effect on operations.

Lines 37-38
m.ext[:variables_ub][name] = lb
m.ext[:variables_lb][name] = lb

**Comment by manuelma** [comment]
Thanks very much! I remember this one was a real headache. We probably fix it in dev but forgot to merge it into master...

**Comment by mihlema** [comment]
This bug is fixed, closing issue.
