### ISSUE TITLE
Drop _lazy_include_file_paths from SpineOpt module

### ISSUE THREAD

**Issue by mihlema** [Spine-project/SpineOpt.jl#403]
This had been introduced to reduce compilation time for SpineOpt, if JuMP and the following are not used. But this usually just means that this compilation has to happen later, and it comes with some incompatibilities with making proper use of Revise (at least for me) and with building the docstrings for our documentation (if we want to do that at some point).

**Comment by manuelma** [comment]
The main purpose here was to be able to call the `load_template` function without having to wait the 6+ seconds it took to `using SpineOpt`. I'm not opposed to get rid of it *but*

1. We'd need an alternative solution to load the template using a julia tool, **if we really want to do that**. I thought the "Load Template" tool could be a good tool for many workflows, but I'm not 100 % sure. Any thoughts on this?
2. The lazy package loading is implemented using the Requires.jl package. It seemed to me at the moment that this is a well supported solution that many other packages are using successfully, so one option should be to try to do it good, so it doesn't interfere with Revise.jl and our docs building. Revise.jl and Requires.jl have the same author so they might eventually work well together?

**Comment by mihlema** [comment]
@manuelma I believe this has been solved? Closing issue.
