### ISSUE TITLE
Output result aggregation functionality

### ISSUE THREAD

**Issue by mihlema** [Spine-project/SpineOpt.jl#404]
To reduce e.g. the size of results written back to the database from SpineOpt, we want to allow the user to have a lower resolution for the results. For this purpose, I want to introduce the following functionality:

- [x] add `output_resolution` for each `temporal_block` (if not defined, this should default to the `resolution` parameter)
- [x] create `output_time_slice` function 
- [x] aggregate result values before writing them to `m.ext[:output]`. For each variable, this output resolution should depend on the `temporal_block` that initializes the variable resolution itself

**Comment by mihlema** [comment]
The last task is a bit tricky. Based on the `time_slices` , for which the variables are defined, we cannot determine, which `temporal_block` was originally used to define the variable. One way to go about this would be to query all `temporal_block`'s of the variable value `time_slice` and take the first `temporal_block`. This is ambiguous for some cases, but I think we can live with this for the moment.

**Comment by mihlema** [comment]
I have decided to go the "simple" aggregation, where we only use the `output` object to define the output resolution. The other option as outlined above is not unambiguous, at least not how it was envisioned. What we could do it to define the resolution on the variable defining relationship, and carry the information along with the variable, but that sounds a bit tedious, and I think this will be sufficient for most cases. Can be closed with #407

**Comment by DillonJ** [comment]
Nice one!

> Codecov Report
> Merging #407 (a7cfdea) into master (cf6f2f6) will decrease coverage by 3.56%.

Just wondering if Are there tests for the new functionality?

**Comment by mihlema** [comment]
Thanks, I'm on it! Should be added there before we merge indeed.

**Comment by manuelma** [comment]
I messed up with this a little bit. The behavior is the following:

- If output_resolution is `null` (the default), then the output (or input, see #408) is written at the highest resolution available. 
- If output_resolution is a duration value, then output values are aggregated at that resolution using `StatsBase.mean`.

**Comment by manuelma** [comment]
Just added test and documentation, it works! Thank you @mihlema !

**Comment by mihlema** [comment]
Great, thank you @manuelma!
