### ISSUE TITLE
`Connection_flow_cost` should be a `connection__to_node` / `connection__from_node` parameter

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/SpineOpt.jl#406]
Similarly to `fuel_cost` and `vom_cost` (which in my opinion should be `unit_flow_cost` as in #405) I think connection_flow_cost` should be a `connection__to_node` / `connection__from_node` parameter rather than a connection parameter as one may wish only to penalise or incentivise flows in a particular direction - which is not possible at present (which I had need of doing today). 

Thoughts?

**Comment by mihlema** [comment]
Yes, that sounds almost like a bug. Feel free to change that

**Comment by manuelma** [comment]
Done using the migration framework, seems to work. Data structure version is now 3 :)
