### ISSUE TITLE
Writing of inputs to output DB

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/SpineOpt.jl#408]
So I've been wanting to do this for a while. A classic case is for diagnostics - in particular I would like to output the demand parameter to the output datastore.

The main reason I want to do this is because SpineOpt is the only place that can output the demand for the appropriate model timeslices. For example, it doesn't work to link the input and output datastores and use an exporter for example - because the demand parameter in the input datastore might be static, or a time pattern or a timeseries with the wrong resolution.

I can't do any kind of meaning diagnostics on some output data if I can't see the demand and the unit flows at the same time.

So I propose to extend the output/report functionality to include input parameters.

As per the existing output/report functionality, we can have a convention for identifying input parameters.

Does the SpineInterface `index()` function give us the correct timeslices and stochastic indices I wonder?

Thoughts? I feel this is an important functionality

**Comment by manuelma** [comment]
Thinking more into it...

We could have an object class called `input` and a relationship class called `report__input`. This would allow to use special rules for reporting inputs, that are independent of those for reporting outputs.

And for reporting inputs, the rule could simply be that we write the value for each natural index (entities) combined with all time slices in the window. What do you think?

**Comment by DillonJ** [comment]
I had a few thoughts in relation to this.

One is if we could combine this with #404 - if we had something like a `maximum_output_resolution` parameter on `report_output` that could work for inputs and outputs. The rule for outputs is that if the natural indices are lower resolution than the specified `maximum_output_resolution`, then they are output at the natural indices resolution, otherwise at the `maximum_output_resolution`. For inputs, it would work similary.

But what are the natural indices for parameters? Can this be determined generically? For example, unit_capacity is determined by the node temporal structure - but how does the code know that?

**Comment by DillonJ** [comment]
I guess `demand` is just an example and you can output other inputs also?

**Comment by manuelma** [comment]
I think this is better after above commits. See https://github.com/Spine-project/SpineOpt.jl/issues/404#issuecomment-977754896 for the current behavior.
