### ISSUE TITLE
Fixing `units_on` to result from last window

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/SpineOpt.jl#409]
To implement a stochastic program in SpineOpt, it is desirable in many cases to have the functionality to fix variables to their value from a previous solve. Our particular use case is where we have a deterministic temporal block representing the realisation followed by a stochastic temporal block representing future forecasts. Consider this temporal structure for example: 

![image](https://user-images.githubusercontent.com/7080191/137486434-80331df7-1425-4f5a-b8c2-6715415c20ec.png)

Here, in window 2 we may wish to fix units on in TB1 to their corresponding solve value from TB2 in window 1, for some units. This is capturing the fact we are bound to decisions made based on forecasted information that cannot be changed at short timescales (commitment status of slow units, if they're on, they're on).

The easiest would be a unit parameter, say `fix_units_online_duration` that would fix the value for units_on for the first `fix_units_online_duration` hours to it's value from the last window. However, there is no guarantee this will "line up" with your TB structure. It also has the advantage that you can vary the number of hours per unit which is very nice.

An alternative is a method parameter (say `fix_units_on_to_last_window`) on `units_on__temporal_block` that would fix the value in the current window for this TB to the solve value from the previous window. However, this would mean explicitly defining `units_on__temporal_block` and not allow us to use the default which is less convenient for the user. It also doesn't allow a different duration for different units unless we create multiple TBs which is very impactical.

My preference is the unit parameter - it's the simplest solution, allows us to use the defaults and can vary easily by unit. It will also be a convenient basis for doing the same for other variables without a massive mess of tb relationships 

Thoughts?

**Comment by DillonJ** [comment]
@manuelma 
> Another thought: is this at all related to the min_up_time?

It could be, but it depends what the user is trying to do, so we shouldn't enforce a connection.

I agree that `units_on_non_anticipativity_duration` is long - but I don't see a way of shortening without abbreviating and losing meaning. It's probably worth keep the additional characters.

**Comment by manuelma** [comment]
How about `units_on_non_anticipativity_time`?
