### ISSUE TITLE
HiGHS Solver is Promising - Some tests

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/SpineOpt.jl#423]
Hi folks,

I came across the HiGHS solver project some time ago in [a LinkedIn post](https://www.linkedin.com/feed/update/urn:li:activity:6870320714684149760?updateEntityUrn=urn%3Ali%3Afs_feedUpdate%3A%28V2%2Curn%3Ali%3Aactivity%3A6870320714684149760%29) and these results caught my attenion

![image](https://user-images.githubusercontent.com/7080191/148690888-11570fd5-4025-48c0-8ca9-788a48736035.png)

[HiGHS project repository](https://github.com/ERGO-Code/HiGHS)
[Description and docs](https://www.highs.dev/).

It's a performant LP and MIP solver. I think this is really exciting and we should do everything we can to support it. To this end, I have written up my instructions on how to use it. Normally, it would just be a matter of adding HiGHS.jl, but for now, it's a little more complicated.

I decided to do some testing with SpineOpt. I ran a full yearly investment model of a small system for a month at hourly resolution with no measures to reduce the size (i.e. I don't use rep days or decomposition). The results I got are as follows:
CPLEX: 7 seconds
HiGHS: 333 seconds
Cbc: 1600 seconds

Obviiously this is just a single model and more thorough testing would be required, but it's very promising that it does so much better than Cbc. My suspicion is that CPLEX gets lucky with some heuristics early in the algorithm.

To use HiGHS isn't straigtforward at the moment - I needed to compile the windows binaries myself using CMake and MSVC which I had to download specially to do, after failing with CodeBlocks (known issue).

The reason I had to compile the binaries myself is that the option to terminate when a certain `mip_gap` is achieved wasn't implemented but was very kindly and promply added by @lgottwald when I suggested this. Here are the steps I needed to follow to use HiGHS if anyone wants to. HiGHS is used by installing HiGHS.jl which usually takes care of the binaries too. These steps will become a lot easier once development stabilises. My understanding that HiGHS.jl will be updated to support all tagged releases of HiGHS.

To compile the binaries you can follow these steps or contact me and I can make the Window x64 binary available. Otherwise:

```
 - Clone HiGHS repository from here https://github.com/ERGO-Code/HiGHS
 - Install CMake
 - Install Microsoft Visual Studio 
 - Run cmake-gui.exe (in my case in c:\program files\cmake\bin\cmake-gui.exe)
 - Specify location of cloned source. Make sure to specify the high-level HiGHS folder (not the /src folder)
 - Create build folder and specify build location
 - Select "Visual Studio 17 2022" as the generator
 - Choose build target architecture
 - Press configure, then generate. This generates an MSVS project file from the source
 - Open the generated MSVS project file with MSVS, it should be called HiGHS.sln in the \build folder
 - Specify "Release" and x64 in the build target dropdowns
 - You should find your compiled highs.dll in \build\bin\release
 ```
In my case I had to rename the compiled highs.dll to libhighs.dll

In julia

```julia
 pkg.add("HiGHS") 
 pkg.add("HiGHS_jll") # this package wraps the binaries that HiGHS.jl uses/
```
Override the binary that HiGS_jll is using by creating a file called `LocalPreferences.toml` containing the below, replacing your path with mine and placing it in the active project folder.

```
[HiGHS_jll]
libhighs_path = "C:\\Workspace\\Spine\\HiGHS\\build\\bin\\Release\\libhighs.dll"
```

Then in Run_SpineOpt:

```julia

using SpineOpt
using JuMP
using HiGHS

mip_solver = optimizer_with_attributes(
		HiGHS.Optimizer, 
		"presolve" => "on",
		"mip_gap_limit" => 0.05
)

lp_solver = optimizer_with_attributes(HiGHS.Optimizer)

m = run_spineopt(
	ARGS...,
	mip_solver=mip_solver,
	lp_solver=lp_solver
)


```

**Comment by jkiviluo** [comment]
Very nice and great to have clear instructions. Shouldn't this go to the SpineOpt documentation?

HiGHS is certainly very promising, but there is something fishy about the CBC results in that post you linked. CBC uses CLP under the hood for LP problems. In that post CLP underperforms GLPK by a factor of two. However, CLP has been much faster than GLPK with FlexTool (which uses only open solvers). So, I suspect that the CBC settings have not been configured properly. CLP could be close to HiGHS (for LP), but it seems that HiGHS has very active development and is therefore a very nice solver to start using.

Another one to check out is SCIP (free only for academic purposes): https://www.scipopt.org/.

**Comment by DillonJ** [comment]
I believe all these tests were on MIP problems but that is not extremely clear... but assuming they are, then would that explain things?

I had a look at the documentation and we don't say anything about configuring solvers at all. We should probably have a high-level article on this.

**Comment by jkiviluo** [comment]
They were just testing with LP. I asked in the forum post.

Indeed, there should be a generic solver page with optional advice sections for specific solvers.

**Comment by DillonJ** [comment]
Highs version 1.2 has been released and HiGHS.jl has been updated accordingly.  This version includes many performance improvements and bug fixes.

Using it is now trivially simple.

`Pkg> add HiGHS.jl

Then, in RunSpineOpt:

```julia
mip_solver = optimizer_with_attributes(
		HiGHS.Optimizer, 
		"presolve" => "on",
		"mip_rel_gap" => 0.05,
		"threads" => 8
	)
lp_solver = optimizer_with_attributes(HiGHS.Optimizer)

m = run_spineopt(
	<urls-dont-touch-this>,
	mip_solver=mip_solver,
	lp_solver=lp_solver
)
```

**Comment by mihlema** [comment]
HiGHS is supported in SpineOpt now, so issues can be closed.
