### ISSUE TITLE
run_migrations() takes forever to complete.

### ISSUE THREAD

**Issue by njjza** [Spine-project/SpineOpt.jl#424]
Hi, I am trying to run the spine-cs-a2 on my local machine. 

The SpineOpt gave me an warning message because database does not include several parameters, and suggested to have "upgrade = true" in function call. After I have the "upgrade = true" clause included in my function call, the run_spineopt() never stops, and the last console message is "Upgrading data structure to the latest version... "

My OS Version: WSL2 Ubuntu 20.04
SpineOpt Version: 0.6.3
Spinetoolbox Version: 0.6.5

**Comment by manuelma** [comment]
Hi! thank you for this. Can you provide your db file so I can try this out?

**Comment by njjza** [comment]
[input.txt](https://github.com/Spine-project/SpineOpt.jl/files/7884578/input.txt)
Hey, this is the input database file written in sqlit. I changed it's extension to .txt just to pass the github's filtration;  The origin file extension is .sqlite.

**Comment by njjza** [comment]
> Hi! thank you for this. Can you provide your db file so I can try this out?

Hi, thanks for the replying. I got the model running now, re-import the database using the spineopt_template. I have a new problem, which is after the spingopt is finished, the output database remained empty.

**Comment by mihlema** [comment]
Hi there,
thanks for reaching out. I had a quick look at the case study. The problem seems to be that the model of this case study is currently infeasible. I will have a look why that is and will get back to asap.
