### ISSUE TITLE
Spine opt is not executed in Spinetoolbox

### ISSUE THREAD

**Issue by OliverLinsel** [Spine-project/SpineOpt.jl#453]
Hello everyone,

after trying to install and perform small optimization calculations I ran into an issue that I cannot really identify. So far I installed the miniconda 3.8 environment, the Julia 1.7.2 environment as well as the current SpineToolbox Client and SpineOpt packages. I used the Installation from sources using Git. The Toolbox seems to work fine, while the execution of the Spine Optimization seems to run into some kind of trouble.

I found the webinar recording on YouTube and tried to build the examples from the workshop as well as the Simple System tutorial and the Case Study A5. After reading about the possible issues with templates from different versions, I already tried to use the newest version from the repository. As you can see in the attached Screenshot, when hitting the execute button in spine toolbox, the database process ticks of and goes on to the Run SpineOpt1 PlugIn process block. There the small hammer keeps on moving while the console in the bottom left says “See console for messages”. The respective Run SpineOpt1 console shows only the message: “2-element Vector (String)” and two IP-adresses. This is where the process stops and remains until it is manually stopped. Since I cannot find any additional issue messages from the console or any other supplementary information, I ran into some kind of dead end with my attempts of troubleshooting.
Maybe you know exactly where the problem might come from. If not, is there a list of common issues and how to solve them or maybe a checklist to check whether the software versions match? I could not find any issue in the repository yet that matches my situation, but maybe I overlooked it. Or is there a debugging mode to get additional information from the system?

![20220504 Screenshot SpineToolbox console message](https://user-images.githubusercontent.com/104202296/166966363-5f276fc9-a976-4672-a8d5-1a51ba9a37fd.png)

Thankfully, Jody gave me a hint to not look into the SpineToolbox console, but in the Anaconda console which gives the following console message after manually stopping the process:

[Spinetoolbox error code.txt](https://github.com/Spine-project/SpineOpt.jl/files/8632893/Spinetoolbox.error.code.txt)

Following this, it looks like some kind of error concerning the internal server connection.

It is absolutely possible, that it is some simple mistake I made while installing or implementing the software and model, but at this moment I cannot find it myself.

Thank you very much in advance and best regards
Oliver

**Comment by DillonJ** [comment]
Thanks again @OliverLinsel for your interest in Spine.

@manuelma do you know what might be going on here? It looks perhaps like a sockets issue?

**Comment by manuelma** [comment]
Thanks @OliverLinsel 
Does this happen every single time you execute the project?

**Comment by OliverLinsel** [comment]
Most of the time. Sometimes it skips the "Run SpineOpt1" process.
 
![grafik](https://user-images.githubusercontent.com/104202296/167084255-38dcf4a4-6248-4487-b1aa-98ef140fc4b7.png)

This is the respective console message in these cases:

[Spinetoolbox error when it skips the RunSpineOpt.txt](https://github.com/Spine-project/SpineOpt.jl/files/8638238/Spinetoolbox.error.when.it.skips.the.RunSpineOpt.txt)

**Comment by manuelma** [comment]
Thank you! I need to investigate, it's a socket problem indeed. Which windows version are you using?

**Comment by OliverLinsel** [comment]
Thank you for looking into it. The Windows version is:

Edition	Windows 10 Pro
Version	21H1

**Comment by manuelma** [comment]
Thank you again. I wonder, can you try running the below python script from your anaconda prompt, with the spinetoolbox environment activated? Just unzip and run it with python socketex.py. The script just runs a simple socket client server exchange, it's just to make sure that the simplest possible socket application works alright.

[socketex.zip](https://github.com/Spine-project/SpineOpt.jl/files/8638468/socketex.zip)

**Comment by OliverLinsel** [comment]
(base) C:\Users\oliver>python socketex/socketex.py
client sends b'hello' (thread 7612)
server receives b'hello' and sends it back (thread 14620)
client receives b'hello' (thread 7612)

(base) C:\Users\oliver>python socketex/socketex.py
client sends b'hello' (thread 11396)
server receives b'hello' and sends it back (thread 2420)
client receives b'hello' (thread 11396)

(base) C:\Users\oliver>python socketex/socketex.py
client sends b'hello' (thread 9128)
server receives b'hello' and sends it back (thread 16600)
client receives b'hello' (thread 9128)

That seems to work fine.

**Comment by manuelma** [comment]
Thanks. Let's try something else if you don't mind. In the case where it skips SpineOpt execution, can you select the Tool to see the julia console at the bottom, and then run any command like `1+1`? Does it work? If not, do you get the ConnectionResetError in the anaconda prompt?

**Comment by OliverLinsel** [comment]
Yes, that works as well.

![grafik](https://user-images.githubusercontent.com/104202296/167098000-b65112ff-f409-4797-bd17-368a46730207.png)

**Comment by manuelma** [comment]
It seems like an intermittent problem -might be difficult to debug. Running the `1+1` command in the julia console and running the SpineOpt tool uses the exact same source code. In some cases we see the issue, in some other cases we don't. May I ask you, can you run the `1+1` multiple times? Does it work every single time? Does running SpineOpt fails every single time?

**Comment by mihlema** [comment]
@manuelma could this otherwise be a problem with SpineOpt itself? It might also be related to #452.

**Comment by OliverLinsel** [comment]
In the case where it skips the SpineOptProcess, the 1+1 operation works every time. The only additional thing I noticed is, that if you do it to fast, the Toolbox freezes.
In the case where the workflow is stuck in the SpineOptProcess the 1+1 operation does not work, but this is probably the case because the workflow is stuck midway.
RunningSpineOpt fails every time.

**Comment by CyrilChambe** [comment]
Hello everyone,

I also face the issue Oliver explained with SpineOpt running endlessy. in my case this happens every single time I execute the project (case study A5).  
I can not figure out what is happenning but I feel the socket error is only due to manual stopping of the process.
I don't know if it has something to do with that, but trying to update SpineOpt in the Settings/Tools window the SpineOpt Installer says "SpineOpt is not installed" although I have just installed it. Could you give me some clues on how to possibly overcome this issue ?

Thanks in advance for your help,

Best, 
Cyril

**Comment by DillonJ** [comment]
Thanks @CyrilChambe for posting. Do you have any messages in the console window from which you launched Spine toolbox?

How did you install Spine toolbox and SpineOpt? By cloning the git repo, or via pip?

@manuelma how can we diagnose this sockets issue?

**Comment by DillonJ** [comment]
Hi all,

So the latest version of SpineOpt and SpineInterface was not available on our Julia registry. We have just registered the latest version so you can update to this version using the readme instructions, copied below for convenience. This may solve your problem. If it doesn't, please report back.

Upgrading
SpineOpt is constantly improving. To get the most recent version, just:

Start the [Julia REPL](https://github.com/Spine-project/SpineOpt.jl/raw/master/docs/src/figs/win_run_julia.png).

Copy/paste the following text into the julia prompt (it will update the SpineOpt package from the [Spine Julia Registry](https://github.com/Spine-project/SpineJuliaRegistry)):

using Pkg
pkg"up SpineOpt"

**Comment by CyrilChambe** [comment]
Hello,
I installed SpineToolbox cloning the git repo and SpineOpt from the Julia REPL.

I get the exact same messages Oliver had in the console :
[AnacondaPromptErrorSkippingSpineOpt.txt](https://github.com/Spine-project/SpineOpt.jl/files/8668848/AnacondaPromptErrorSkippingSpineOpt.txt)
[AnacondaPromptErrorManualStopping.txt](https://github.com/Spine-project/SpineOpt.jl/files/8668849/AnacondaPromptErrorManualStopping.txt)
 And I also get this message in the spinetoolbox julia console :
[JuliaErrorStoppingSpineOpt.txt](https://github.com/Spine-project/SpineOpt.jl/files/8668854/JuliaErrorStoppingSpineOpt.txt)
 
Updating SpineOpt did not change anything.

**Comment by DillonJ** [comment]
That's great news - although it would be great to understand why it doesn't work on the first attempt. Does it fail first time every time?

@OliverLinsel hopefully updating SpineOpt will help for you also - please let us know!

**Comment by manuelma** [comment]
Looking at the error messages, they don't seem to have anything to do with SpineOpt. The error happens in spinetoolbox. I'm thinking that a solution could be to simply retry the socket communication if the connection is reset - it might be a small synchronization issue. Will try to implement that.

**Comment by manuelma** [comment]
Should work better after above commit, so you should just update your spinetoolbox version including requirements following the instructions in the README. Thanks very much for reporting! Please keep us posted :)

**Comment by soininen** [comment]
Looking at this line:

> (spinetoolbox) C:\Users\oliver>pip install -r requirements.txt

`C:\Users\oliver` is probably a wrong directory to run `pip` in. You need to `cd` into the same directory into which you cloned the Toolbox git repository, e.g. `C:\Users\oliver\Spine-Toolbox`. The `requirements.txt` file should be in the same directory.

Please note, that you should update pip before trying to install Toolbox requirements since with certain versions of pip the operation takes ages. This is done with `pip install --upgrade pip`

**Comment by OliverLinsel** [comment]
Hello everyone,

first of all thank you very much for your responses. Especially the comment concerning the installation directory was helpfull. Installing via requirements.txt did work now. I also updated to the most recent version via:
`pip install -U -r requirements.txt`
The now installed versions are

![grafik](https://user-images.githubusercontent.com/104202296/172600148-e63e77e1-1fa9-441f-a88c-e3fcdd06e64c.png)

(Actually this updating to the current development version failed the first time I tried and came out with some kind of version error, but was succesfull in my second attempt with freshly downloaded source code from the repo)

Unfortunately the error code still seems to remain the same as it was initially:
[20220608 SpineOpt not executed.txt](https://github.com/Spine-project/SpineOpt.jl/files/8860921/20220608.SpineOpt.not.executed.txt)

Yes, I tried the `Load template` tool some time ago but without success. (There was a video on Youtube which I followed step by step) It seems that the templates are not always working. The template I am using is one I got from a colleague who was successful with the simple systems tutorial.

How would I run SpineOpt from outside the spine toolbox? Is there a README?

Thank you very much and best regards
Oliver

**Comment by DillonJ** [comment]
Hi Oliver,

I'm sorry you are having trouble. It looks like this is the sockets issue again which we thought we had robustly solved. @manuelma any ideas?

But you are right, running SpineOpt directly from Julia will bypass the sockets interface and use PyCall instead. But PyCall needs to be configured to use the same Julia your toolbox is running as by default, it will use its own. You can find the PyCall instructions here https://github.com/JuliaPy/PyCall.jl but you basically need to set the path to your Tooblox Conda environment as follows:

```Julia
using Pkg 
ENV["PYTHON"] = "/Users/name/opt/anaconda3/envs/mlbasic/bin/python"
Pkg.build("PyCall")

```
The documentation regarding how to run SpineOpt directly from Julia are here: https://spine-project.github.io/SpineOpt.jl/latest/library/#Public-interface

But basically, you will need to run the below code - either as a file or directly from the Julia REPL:

```Julia
using SpineOpt
m = run_spineopt(
    raw"sqlite:///C:\path\to\your\inputputdb.sqlite", 
    raw"sqlite:///C:\path\to\your\outputdb.sqlite";
    filters=Dict("tool" => "object_activity_control", "scenario" => "scenario_to_run")
    alternative="your_results_alternative"
)
```

If you just have the base scenario in your model, then you can omit `"scenario" => "scenario_to_run"`

Let us know if that works for you.

**Comment by jkiviluo** [comment]
Jody, should your nice code snippet example also be in https://spine-project.github.io/SpineOpt.jl/latest/library/#Public-interface?

**Comment by DillonJ** [comment]
@jkiviluo Good point! I'l do that now

**Comment by mihlema** [comment]
Hi all,
@OliverLinsel and I figured out the problem this morning. 

It seems that the JuliaRegistry version of SpineInterface was outdated. Manually installing the latest SpineInterface version with
`] add https://github.com/Spine-project/SpineInterface.jl `
resulted in the desired update, and we could resolve the issue. Thanks @OliverLinsel for hanging in there!
