### ISSUE TITLE
Constraint `units_on` across scenarios

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/SpineOpt.jl#472]
Hi folks,

I'm trying to get a stochastic model working. What I want is a single deterministic scenario, 15 mins resolution from hours 0 to 6. Then I want 6 scenarios from 6h onwards. However, I want `units_on` from 6h onwards to be deterministic - i.e. have the same value for all scenarios. If I try having a deterministic scenario in hours 6h onwards... it doesn't work, because it looks for parameter values for this scenario and doesn't find them. I might be wrong, but it feels like we need new functionality to achieve this. I can immediately think of two ways around this... a new constraint based on a method parameter that will constrain `units_on` to have the same value across all scenarios - I don't like this as it creates additional variables - but maybe its ok as the presolve should eliminate them. The other is some way to designate a scenario as a master scenario... that would map the variables associated with it to the other scenarios. For now, the first way seems easier. But am I missing anything? Given the existing functionality, is there a way for me to constrain `units_on` to have the same value across all scenarios?

**Comment by DillonJ** [comment]
Actually, this works perfectly fine and I should apologise to @Tasqu for doubting the elegance of the system. It’s really quite powerful. All I was missing was making sure units on for units with stochastic production, is also stochastic

**Comment by Tasqu** [comment]
@DillonJ No apologies necessary 😄 I had almost forgotten about the existence of the [`units_on__stochastic_structure`](https://spine-project.github.io/SpineOpt.jl/latest/concept_reference/Relationship%20Classes/#units_on__stochastic_structure) relationship myself.
