### ISSUE TITLE
Early developer meetings - JFYI

### ISSUE THREAD

**Issue by mihlema** [Spine-project/SpineOpt.jl#473]
### :loudspeaker:UPDATE: Community :rocket: 

To connect with other users, to identify problems and exchange experiences, we will organize monthly early-user meetings for Spine Toolbox and SpineOpt. The meetings will be held first Tuesday of every month at 3pm CEST [:calendar: ics zip](https://github.com/spine-tools/SpineOpt.jl/files/10497817/Spine.Toolbox.and.SpineOpt_.Exchange_.Q.A_.Help.zip)
and can be joined [here](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MTA4MTZmMjMtNzk0ZS00ZjFkLWFjZjEtODVhNDc3Yjg5MjBj%40thread.v2/0?context=%7b%22Tid%22%3a%22021f8f00-6328-4916-b79c-b49b9a19a7d6%22%2c%22Oid%22%3a%22f45e2eeb-78d8-4230-903d-49e42a141be3%22%7d)..

Might be interesting for you @OliverLinsel @CyrilChambe @Mathias157 @LeoniePlaga @rputris @fbozzolo @RowanPeng. Feel free to spread the word.

**Comment by OliverLinsel** [comment]
Thank you very much Maren! Looking forward to it :)

**Comment by Mathias157** [comment]
Thanks a lot for the notification, @mihlema. I will be there!

**Comment by Mathias157** [comment]
Hi all,

Here's a DataInput sample of my renewable fuel model, that I will present in tomorrow's Early developer meeting.
Note that this probably only works with older versions of SpineOpt and SpineToolbox:
- SpineOpt v0.6.3
- SpineToolbox v0.6.5

The resolution of the model is set to 4 timesteps, for quick solving, and 6 nodes (spatial resolution).

[REfuelModel.zip](https://github.com/Spine-project/SpineOpt.jl/files/10115110/REfuelModel.zip)

**Comment by mihlema** [comment]
Dear all,
as of January, 10 am CET is not feasible for me anymore. I'd alternatively propose to have the meeting at 4 pm CET. Could you quickly signal with a thumbs up/down if this would work for you? (Otherwise, I'll just create a doodle)

**Comment by DillonJ** [comment]
### Parameter Defaults

A quick thought I had from last meeting... let me know if there is a better place to post such thoughts/discussions...

Use of parameter value defaults in SpineOpt should be used with a healthy degree of caution since many constraint equations are written based on the absence, presence or value of the default. It should be viewed as a developer setting. When a default  is specified, it means that every entity of the relevant class will have a value for that parameter, whether it's one explicitly set, or the default value. Some constraints filter variable and/or constraint indices by whether they have values for a certain parameters, so specifying a default for a parameter that didn't have one originally can potentially lead to decreasing performance and/or unintended behaviour. I think @mihlema experienced this before and it can be difficult to debug!

**Comment by mihlema** [comment]
> ### Parameter Defaults
> A quick thought I had from last meeting... let me know if there is a better place to post such thoughts/discussions...
> 
> Use of parameter value defaults in SpineOpt should be used with a healthy degree of caution since many constraint equations are written based on the absence, presence or value of the default. It should be viewed as a developer setting. When a default is specified, it means that every entity of the relevant class will have a value for that parameter, whether it's one explicitly set, or the default value. Some constraints filter variable and/or constraint indices by whether they have values for a certain parameters, so specifying a default for a parameter that didn't have one originally can potentially lead to decreasing performance and/or unintended behaviour. I think @mihlema experienced this before and it can be difficult to debug!

I think it's great to keep notes on these recommendations. I think we should probably include such things in the Documentation, and add a section there "best practice" or something

**Comment by mihlema** [comment]
Regarding scheduling a new regular meeting as of January, it's probably afterall easiest if we just use a [doodle](https://doodle.com/meeting/participate/id/avlyxynd).

**Comment by mihlema** [comment]
Happy New Year!
According to the doodle, a possible date for our recurring calls could be Tuesday morning at 3pm CE(S)T. If you still want to vote, go ahead. I will otherwise update the calendar invite in the coming days.

**Comment by DillonJ** [comment]
Hi folks... it looks the calendar invite wasn't updated. Tuesday 3pm CE(S)T works for me... I propose updating the calendar invite

**Comment by DillonJ** [comment]
Hi folks - I edited the original post with an updated calendar invite for  Tuesday 3pm CE(S)T

**Comment by mihlema** [comment]
Thanks for taking care of this @DillonJ !

**Comment by mihlema** [comment]
@lilanger sorry for the confusion. This is the issue where we update on changes. Also, JFYI, linking you to the issue too @RowanPeng, @josefkoell,

**Comment by mihlema** [comment]
Tomorrow is going to be our next meeting! looking forward to talking to you all. Also in case you missed it, spine-tools is now on [gitter](https://matrix.to/#/#spine-tools_community:gitter.im) :)

**Comment by lilanger** [comment]
Hi all
I also created the two repositories we talked about last time, for standardized results and visualization and cluster runs:
https://github.com/spine-tools/spine-DTU-visualization
https://github.com/spine-tools/spine-cluster

Hope you find them helpful.

**Comment by mihlema** [comment]
Hi all,
not sure if anyone is trying to join the call today. @DillonJ in case you're around, the meeting can't be started without you I am afraid. I am guessing that probably many people are on holidays anyways this week, so I'd suggest to just skip this instance otherwise?

**Comment by RowanPeng** [comment]
Hi,

Thanks for this email. I would like to join the meeting, if you still
schedule one.

Regards,

Peng

Maren Ihlemann ***@***.***> 于2023年8月1日周二 14:07写道：

**Comment by mihlema** [comment]
Hi all,
just coming of our monthly call, and wanting to make sure that those calls are still useful for everyone and would like to hear your feedback on those calls, and how we can improve them going forward. Feel free to post here, or if you prefer, you can also reach out to me via [gitter](@mihlema-5c0540c5d73408ce4fb0cdae:gitter.im) or e-mail.

**Comment by lilanger** [comment]
Hi all,
I enjoy these calls quite a lot and find them super helpful. To get updates from the Mopo project is very interesting, that would be nice to have on a regular basis. I guess the amount of questions comes in waves (also with the academic year). It would be nice to see some of the work people have been doing using SpineOpt, so if people would come back to share their success stories in a way.

**Comment by mihlema** [comment]
Hi all,
as discussed during our last meeting, we will reconvene next week Tuesday for our next user meeting. @DillonJ we should just be able to use the "standard" link, I guess? Otherwise, could you possibly send another invite here for the updated meeting? Thanks!

**Comment by mihlema** [comment]
https://teams.microsoft.com/l/meetup-join/19%3ameeting_MTA4MTZmMjMtNzk0ZS00ZjFkLWFjZjEtODVhNDc3Yjg5MjBj%40thread.v2/0?context=%7b%22Tid%22%3a%22021f8f00-6328-4916-b79c-b49b9a19a7d6%22%2c%22Oid%22%3a%22f45e2eeb-78d8-4230-903d-49e42a141be3%22%7d

**Comment by lilanger** [comment]
Just adding the colleagues from CBS for updates: @weibezahn @hannesfelipe
