### ISSUE TITLE
`vom_cost` not work with `nodegroup`

### ISSUE THREAD

**Issue by nnhjy** [Spine-project/SpineOpt.jl#495]
SpineOpt fails when `vom_cost` is used in units linking to a `nodegroup`. Try and see the error with this DB: 
[Data Store input_1.zip](https://github.com/Spine-project/SpineOpt.jl/files/9779131/Data.Store.input_1.zip).

In comparison, if we replace the `vom_cost` of `unitB` with `fuel_cost`, the model works as usual.

The indices of `vom_cost` seem not adapted to handle `nodegroup`. There might be other parameters having this issue.

**Comment by mihlema** [comment]
This should be fixed now.
