### ISSUE TITLE
connection_capacity constraint linked to temporal resolution of invest temporal_block

### ISSUE THREAD

**Issue by kTelaar** [Spine-project/SpineOpt.jl#715]
Hi everyone,

I noticed an issue when investing in connection capacity with varying temporal resolutions present, e.g. 2 different temporal_blocks: 
1. "hourly" resolution of 1h, model__default_temporal_block 
2. "invest" resolution of 1M, model__default_investment_temporal_block

While the resulting connection flow through the invested connection is shown in a resolution of 1h in the outputs, the constraint of invested_connections * connection_capacity =< maximum flow seems to be applied to the resolution of 1M (or in the case where model_end is shorter than the 1M "invest" resolution: the complete modeled duration).

For example
- input config of connection_capacity: 1000.0
- output variable connections_invested: 1.0

resulting in (shown in plot below) 
- connection_flow maximum 10319.8126 (peak per hour) 
- connection_flow average 1000.0 (average per hour, during 336h)

![SA-BRA-CN_SA-BRA-NE](https://github.com/spine-tools/SpineOpt.jl/assets/140422859/49596474-9271-4763-9633-8e3cca9468c0)

A comparison to established connections that are not investment candidates showed the expected behaviour of connection_capacity correctly limiting the maximum flow per hour, while the invested connection seems to limit the maximum flow per month (or in this case to the average through the modeled 336h).

I've included the input config and output results of the mentioned connection and a different one with 644 MW invested capacity in an Excel File as well.
[20230724 input and output bug report connection invest.xlsx](https://github.com/spine-tools/SpineOpt.jl/files/12148308/20230724.input.and.output.bug.report.connection.invest.xlsx)

Many thanks, 
Konrad

 - SpineOpt: 
[0cda1612] SpineInterface v0.11.1
[0d8fc150] SpineOpt v0.6.13
 - Toolbox:
spinetoolbox 0.6.15
spinedb_api 0.24.0
spine_engine 0.19.0
spine_items 0.17.0
Python 3.8.1 (default, Mar  2 2020, 13:06:26) [MSC v.1916 64 bit (AMD64)]
- Win10 Pro

**Comment by kTelaar** [comment]
adding to this: in the "constraint_connection_flow_capacity.jl" you commented on the here observed behaviour

"for situations where the same `connection` handles `connection_flows` to multiple `nodes` with different temporal resolutions, the constraint is only generated for the lowest resolution, and only the average of the higher resolution `connection_flow` is constrained."

I don't think it should apply in this context though because the investable (`candidate_connections` = 1.0) connection connects the same exact nodes that the established connection (`candidate_connections` = None) connects as well. The only difference seems to be that the `connection_flow` is constrained in the first case by the resolution of `model__default_investment_temporal_block` and in the second case by the resolution of `model__default_temporal_block`.

**Comment by DillonJ** [comment]
I confirm that this is an issue, thanks @tokorte  - @manuelma could you please take a look
